# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19jQ_60KKOjSjKWt_B6_T_87rKDg4CB4L
"""

from flask import Flask, request, send_file

import pandas as pd

import pdfplumber

import tempfile

import os

app = Flask(__name__)

@app.post("/convert")

def convert_pdf():

    file = request.files['file']

    with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as temp_pdf:

        file.save(temp_pdf.name)

        tables = []

        with pdfplumber.open(temp_pdf.name) as pdf:

            for page in pdf.pages:

                table = page.extract_table()

                if table:

                    tables.append(table)

        df = pd.DataFrame([row for table in tables for row in table])

    out_path = tempfile.NamedTemporaryFile(delete=False, suffix=".xlsx").name

    df.to_excel(out_path, index=False)

    return send_file(out_path, as_attachment=True, download_name="output.xlsx")